name:               SeHan Kim's blog
title:              Seize The Day!
email:              ksh2594@gmail.com
description:        'Notes and thoughts from SeHan'
author:             SeHan Kim
baseurl:            "/"
url:                "https://coreash.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  sehan.kim.79
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-49993718-2 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
