name:               또치's blog
title:              Seize The Day!
email:              ksh2594@gmail.com
description:        '여행, 세계여행, 바둑, 개발, 일상, 생각, trip, travel, baduk, badook, go, development, life, life style, thinking '
author:             또치
baseurl:            "/"
url:                "https://coreash.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  sehan.kim.79
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-49993718-2 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
